version: "3"

services:
  rng:
    build: dockercoins/rng
    image: ${REGISTRY_SLASH-localhost:5000/}rng${COLON_TAG-:latest}
    deploy:
      mode: global

  hasher:
    build: dockercoins/hasher
    image: ${REGISTRY_SLASH-localhost:5000/}hasher${COLON_TAG-:latest}

  webui:
    build: dockercoins/webui
    image: ${REGISTRY_SLASH-localhost:5000/}webui${COLON_TAG-:latest}
    networks:
      - tools_traefik-net
    deploy:
      labels:
        - "traefik.port=80"
        - "traefik.frontend.rule=Host:webui.docker.sbr.pm"
        - "traefik.frontend.passHostHeader=true"

  redis:
    image: redis

  worker:
    build: dockercoins/worker
    image: ${REGISTRY_SLASH-localhost:5000/}worker${COLON_TAG-:latest}
    deploy:
      replicas: 10


networks:
  tools_traefik-net:
    external: true
